# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='voted',
            field=models.NullBooleanField(verbose_name=False),
        ),
    ]
