# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_person_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='voted',
            field=models.NullBooleanField(),
        ),
    ]
