# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_totalnumberofvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalnumberofvotes',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
