# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_totalnumberofvotes_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='currentCondition',
            field=models.CharField(default='Not Touched', max_length=100),
        ),
    ]
