# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_person_currentcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='winner',
            field=models.CharField(default='Needs to be decided', max_length=200),
        ),
    ]
