# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uniqueCode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
